# bin/bash!
rails g active_admin:resource Resolucion
rails g active_admin:resource OtraNorma
rails g active_admin:resource Ordenanza
rails g active_admin:resource Especial
rails g active_admin:resource Declaracion
rails g active_admin:resource Proyecto
rails g active_admin:resource Peticion
rails g active_admin:resource Eximicion
rails g active_admin:resource Despacho
rails g active_admin:resource Condonacion
rails g active_admin:resource Administrativo
rails g active_admin:resource ActuacionAdministrativa
rails g active_admin:resource VetoTotalRelationship
rails g active_admin:resource PromulgaRelationship
rails g active_admin:resource VetoParcialRelationship
rails g active_admin:resource DelegaRelationship
rails g active_admin:resource Periodo
rails g active_admin:resource Decreto
rails g active_admin:resource Tramite
rails g active_admin:resource OtraPublicacion
rails g active_admin:resource Comision
rails g active_admin:resource Titulo
rails g active_admin:resource OrdenDelDia
rails g active_admin:resource Clasificacion
rails g active_admin:resource Tag
rails g active_admin:resource Norma
rails g active_admin:resource Circuito
rails g active_admin:resource SuspendeVigenciaRelationship
rails g active_admin:resource ModificaRelationship
rails g active_admin:resource CircuitoOrden
rails g active_admin:resource SubSeccion
rails g active_admin:resource Libro
rails g active_admin:resource CapitulosNorma
rails g active_admin:resource Sesion
rails g active_admin:resource Expediente
rails g active_admin:resource Capitulo
rails g active_admin:resource Seccion
rails g active_admin:resource ExpedienteAdministrativo
rails g active_admin:resource BoletinOficial
rails g active_admin:resource EstadoTramite
rails g active_admin:resource Bloque
rails g active_admin:resource RestituyeVigenciaRelationship
rails g active_admin:resource EstadoExpediente
rails g active_admin:resource BloquePeriodo
rails g active_admin:resource DocumentacionPresentada
rails g active_admin:resource AdReferendumRelationship
rails g active_admin:resource RelationshipConcejal
rails g active_admin:resource Digesto
rails g active_admin:resource ReglamentaRelationship
rails g active_admin:resource DiarioDeSesion
rails g active_admin:resource AdjuntaFisicamente
rails g active_admin:resource ProrrogaVigenciaRelationship
rails g active_admin:resource Destino
rails g active_admin:resource Acumula
rails g active_admin:resource ProrrogaSuspensionRelationship
rails g active_admin:resource DerogaRelationship
rails g active_admin:resource AclaraRelationship
